### PR TITLE
fix(#147): improve handling of anyOf

### LINKED ISSUE #147: anyOf not handled correctly
hey, i think i have come across an issue with the zod schema generated for `anyOf`.

consider the example given in the swagger docs: https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#anyof

it lists a number of valid and invalid requests. the last of the valid requests is like this:

```json
{
  "nickname": "Fido",
  "pet_type": "Dog",
  "age": 4
}
```

but with the given openapi schema, the generated zod schema looks like this:

```ts
const patchPets_Body = z.union([
  z.union([PetByAge, PetByType]),
  z.array(z.union([PetByAge, PetByType])),
]);
```

looking at the swagger docs, i don't think array should be part of this. in this simple example, might this be correct?

```ts
const patchPets_BodyFixed = z.union([
  z.intersection(PetByAge, PetByType), // it seems important to zod that this comes first?
  PetByAge,
  PetByType,
]);
```

effectively `(A & B) | A | B` instead of `A | B | Array<A | B>`

i'm not sure if this gets more complicated when there are more than two `anyOf` options?

Here's a [link to the playground]( https://openapi-zod-client.vercel.app/?doc=AQ4BwQwFwCwZwFwChSgPRgKZUS1pIoBjGZffAJ0wEcBXTOKAIQHsATATzPPyJYDsomQdx74IYMABsAlkWgyBaAFZwBosfjglMAWwgbN4-hwDyAM0NH8AWmAASKpeAByAMRo%2BusAOE402jB6EHBoAArYTBwAggDmmC541jx2jpjO7p4s3r6CoYHBoRHMHAAqHFiJRlRwPvxwDFbkLgBMAAxtLk08bAxEFDJgUIr8CMAAqmBs0JhsScBedX645AX6KzzFUXGY3SBQFbvALABGyphEUPPkYBQsWBTDjcDXPBDxY69iB1hjMoKYeIUL74fhyADW-AguiOIPIPyOjAG-FicOAVDoMiobD2oDs70waNQIK2ZUOuIRY1O50uaNu90wjxkjSJ4GwAH1Kaz9uTgEj-qjkiBhLRdGMANoAYWgABpgAARFixAC6rJgtDyuNQlOAJxYLCkmAg-DRGNoWNmn2SdiwUE5hyAA)

And here's a stackblitz where i've copied the types from the playground and also applied my possible fix. you can see the fix works as described in the swagger docs, whereas the current output does not https://stackblitz.com/edit/typescript-peyk8j?file=index.ts

### PR DESCRIPTION
**Pull request by WickyNilliams**
fixes #147

as far as i can tell, this is closer to the real behavior of json-schema, from which openapi inherits `anyOf`.

in my testing, given two object types `A` and `B`, anyOf these is equivalent to:

```ts
z.union([A.passthrough(), B.passthrough()])
```

that is, `anyOf` is satisfied if any of the types match, and it stops validating after that allowing any additional properties. hence, `passthrough`

primitive types are special cased since passthrough does not make sense for them. resulting in:

```ts
z.union([APrimitiveType, AnObjectType.passthrough()])
```

i've prepared a small playground for experimenting with json-schema behavior, in case it's useful for validating the logic here https://stackblitz.com/edit/json-schema-anyof-test?file=index.tsx

### CODE REVIEW

**Comment by WickyNilliams** [comment]
i'm not convinced the tests i've added here really help with proving the behavior is correct. is there some way that i can get the generated types in a test and call zod's `parse`, asserting the result? that way i can take test cases from json-schema and ensure it matches

File: lib/src/openApiToZod.ts [hunk 1]
```diff
@@ -107,9 +107,22 @@ export function getZodSchema({ schema, ctx, meta: inheritedMeta, options }: Conv
...
-        return code.assign(`z.union([${oneOf}, z.array(${oneOf})])`);
+        const types = schema.anyOf
+            .map((prop) => getZodSchema({ schema: prop, ctx, meta, options }))
+            .map((type) => {
+                let isPrimitive = false;
+
+                if ("type" in type.schema && !Array.isArray(type.schema.type)) {
+                    const schemaType = type.schema.type.toLowerCase() as NonNullable<typeof schema.type>;
+                    isPrimitive = isPrimitiveType(schemaType);
+                }
```
Comment (WickyNilliams) [inline lib/src/openApiToZod.ts:118]: i feel like i'm doing something wrong here since it's so awkward - is there a better way? thought i'd ask, just in case

File: lib/tests/anyOf-matches-json-schema.test.ts [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+                        required: ["pet_type"],
+                    },
+                    { type: "number" },
+                ],
+            },
+        })
+    ).toMatchInlineSnapshot(
+        '"z.union([z.object({ age: z.number().int(), nickname: z.string().optional() }).passthrough(), z.object({ pet_type: z.enum(["Cat", "Dog"]), hunts: z.boolean().optional() }).passthrough(), z.number()])"'
+    );
+});
```
[the remark this answers is not in the document]
Comment (astahmer) [reply lib/tests/anyOf-matches-json-schema.test.ts:78]: there's no way to do that atm, although it would be very useful, but I guess for now you could just copy/paste the result and re-use that in another test with a manual call to the zod parse fn

[the remark this answers is not in the document]
Comment (WickyNilliams) [reply lib/tests/anyOf-matches-json-schema.test.ts:78]: that works! i'll do it tomorrow, just finishing up for the day :)

File: lib/src/openApiToZod.ts [hunk 3]
```diff
@@ -107,9 +107,22 @@ export function getZodSchema({ schema, ctx, meta: inheritedMeta, options }: Conv
...
 
-        const types = schema.anyOf.map((prop) => getZodSchema({ schema: prop, ctx, meta, options })).join(", ");
-        const oneOf = `z.union([${types}])`;
-        return code.assign(`z.union([${oneOf}, z.array(${oneOf})])`);
+        const types = schema.anyOf
+            .map((prop) => getZodSchema({ schema: prop, ctx, meta, options }))
+            .map((type) => {
+                let isPrimitive = false;
+
+                if ("type" in type.schema && !Array.isArray(type.schema.type)) {
```
Comment (WickyNilliams) [inline lib/src/openApiToZod.ts:115]: also, what does it mean for the schema's type to be an array? i couldn't tell if this is TS getting the types wrong or not, so i filtered that out. but does it need to be specifically handled somehow?

Comment (astahmer) [reply lib/src/openApiToZod.ts:115]: it can happen since OpenAPI 3.1

it was introduced [in this PR](https://github.com/astahmer/openapi-zod-client/commit/519de1409be4dbe6efb2c25db58669b3c48f38b7) because of [this issue](https://github.com/astahmer/openapi-zod-client/issues/60)

Comment (astahmer) [reply lib/src/openApiToZod.ts:115]: from what we wrote in this issue:

> it basically acts as a or operator, like the SchemaObject["oneOf"]

Comment (astahmer) [reply lib/src/openApiToZod.ts:115]: yes and yes ! it was handled here by indeed just looping on the `type` and then calling `getZodSchema` using a that isolated type if it's a complex type or just using an union otherwise

https://github.com/astahmer/openapi-zod-client/commit/519de1409be4dbe6efb2c25db58669b3c48f38b7#diff-aff08f665d4e69fe50761cef05035287658147285c711089446e5cbbbadacb54R66-R77

File: lib/tests/anyOf-matches-json-schema.test.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (WickyNilliams) [reply lib/tests/anyOf-matches-json-schema.test.ts:78]: not sure if this is too cursed to commit?

```ts
function createValidator(zodSchema: CodeMeta) {
    return new Function(
        "input",
        `
        with(this) {
            return ${zodSchema}.parse(input)
        }
    `
    ).bind({ z });
}

const zodSchema = getZodSchema({ schema: { type: "number" } })
const validator = createValidator(zodSchema)

expect(() => validator("string")).toThrow()
```

[the remark this answers is not in the document]
Comment (WickyNilliams) [reply lib/tests/anyOf-matches-json-schema.test.ts]: it's easier to beg for forgiveness than ask permission, so i just pushed this haha. it's a quick (and definitely dirty!) way to validate the behavior of schemas produced, but i think it's valuable here. simple to back out if you'd rather not. let me know!

[the remark this answers is not in the document]
Comment (astahmer) [reply lib/tests/anyOf-matches-json-schema.test.ts]: I'm not sure what the `with` keyword does tbh, it's been a while since I saw this 😅  but yeah overall this seems fine, it does the job ! keep it

[the remark this answers is not in the document]
Comment (astahmer) [reply lib/tests/anyOf-matches-json-schema.test.ts]: it looks great !

**Comment by WickyNilliams** [comment]
@astahmer ok i've tested this against my codebase and this seems to fix the previous issues i had (though introduces some new ones as a result of #140), so from my side i think it's complete

File: lib/tests/use-union-only-when-multiple-choices.test.ts [hunk 4]
```diff
@@ -18,5 +18,5 @@ test("use-union-only-when-multiple-choices", () => {
                 },
             },
         })
-    ).toMatchInlineSnapshot('"z.object({ singleOneOf: z.string(), multipleOneOf: z.union([z.string(), z.number()]), singleAnyOf: z.string(), multipleAnyOf: z.union([z.union([z.string(), z.number()]), z.array(z.union([z.string(), z.number()]))]), singleAllOf: z.string(), multipleAllOf: z.string().and(z.number()) }).partial()"');
+    ).toMatchInlineSnapshot('"z.object({ singleOneOf: z.string(), multipleOneOf: z.union([z.string(), z.number()]), singleAnyOf: z.string(), multipleAnyOf: z.union([z.string(), z.number()]), singleAllOf: z.string(), multipleAllOf: z.string().and(z.number()) }).partial()"');
```
Comment (astahmer) [inline lib/tests/use-union-only-when-multiple-choices.test.ts:21]: is this one still valid ? 
other than this change, LGTM we can probably merge it

Comment (astahmer) [reply lib/tests/use-union-only-when-multiple-choices.test.ts:21]: from what I remember and looking at [this comment](https://github.com/astahmer/openapi-zod-client/blob/main/lib/src/openApiToZod.ts#L103)

> // anyOf = oneOf but with 1 or more = `T extends oneOf ? T | T[] : never`

so when I see this: 

```json
{
   anyOf: [{ type: "string" }, { type: "number" }]
}
```

I think of it as:

```ts
type Thing = string | number | (Array<string | number>)
```

which looked kinda ok before:
```diff
- z.union([z.union([z.string(), z.number()]), z.array(z.union([z.string(), z.number()]))])
+ z.union([z.string(), z.number()])
```

and now it looks like :

```ts
type Thing = string | number
```

was it wrong before then or is it now ?

Comment (WickyNilliams) [reply lib/tests/use-union-only-when-multiple-choices.test.ts:21]: i think it was wrong before. anyOf doesn't mean it can be an array. it is a union, that allows any additional properties through (it stops validating after the first type match).

it was kind of hard to find an authoritative source on this, so i looked at the tests from the json-schema repo here. they don't show any use of arrays https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/b069ac352c3dc1fae71f6f177dafe97001c97920/tests/draft2020-12/anyOf.json

i also tested this with `ajv` which is a popular json-schema implementation in js. see here, it fails (as expected) in the array case https://stackblitz.com/edit/json-schema-anyof-test-pnfj13?file=index.tsx%3AL55

Comment (WickyNilliams) [reply lib/tests/use-union-only-when-multiple-choices.test.ts:21]: it would probably be super valuable at some point to lift all those json-schema test cases and run them against the generated zod schemas!

Comment (astahmer) [reply lib/tests/use-union-only-when-multiple-choices.test.ts:21]: ok got it, I checked with this guy and it explains it pretty clearly
https://chat.openai.com/share/954082b4-d72d-4b5f-a0d1-4a2107705ddb

oneOf = exactly 1 match, anyOf = must match 1 or more in the list

I guess we can merge it then if that's fine with you

Comment (WickyNilliams) [reply lib/tests/use-union-only-when-multiple-choices.test.ts:21]: in my testing i don't think the "or more" part is even a requirement - as soon as there's a single match it doesn't care about the rest

```js
{
  anyOf: [
    {
      type: 'object',
      properties: {
        age: {
          type: 'integer',
        },
      },
      required: ['age'],
    },
    {
      type: 'object',
      properties: {
        pet_type: {
          type: 'string',
          enum: ['Cat', 'Dog'],
        },
      },
      required: ['pet_type'],
    },
  ],
};
```

this schema would allow the following data: 

```js
{ pet_type: "Cat", age: "not a number" } // matches PetByType, doesn't care age isn't a number
{ age: 1, pet_type: "Unicorn" } // matches PetByAge, doesn't care about unicorn not being a type of pet
```

so yes! go ahead and merge if you're happy
